/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Players */
        get: operations["search_players_api_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_api_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Ratings */
        get: operations["get_player_ratings_api_players__player_id__ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/playstyles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Playstyles */
        get: operations["get_player_playstyles_api_players__player_id__playstyles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Market */
        get: operations["get_player_market_api_players__player_id__market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Similar Players */
        get: operations["get_similar_players_api_players__player_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{role_key}/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Role Rankings */
        get: operations["role_rankings_api_roles__role_key__rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Methodology */
        get: operations["methodology_api_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Ingest */
        post: operations["trigger_ingest_api_admin_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/recompute-ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Recompute */
        post: operations["trigger_recompute_api_admin_recompute_ratings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rating-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rating Runs */
        get: operations["rating_runs_api_admin_rating_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditBreakdown */
        AuditBreakdown: {
            /** Role Key */
            role_key: string;
            /**
             * Metric Breakdown
             * @default {}
             */
            metric_breakdown: {
                [key: string]: unknown;
            };
            /**
             * Context Breakdown
             * @default {}
             */
            context_breakdown: {
                [key: string]: unknown;
            };
            /**
             * Confidence Breakdown
             * @default {}
             */
            confidence_breakdown: {
                [key: string]: unknown;
            };
            /**
             * Penalties
             * @default {}
             */
            penalties: {
                [key: string]: unknown;
            };
            /** Explanation Text */
            explanation_text?: string | null;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Season */
            season: string;
            /** Role Key */
            role_key?: string | null;
            /** Role Display */
            role_display?: string | null;
            player_a: components["schemas"]["CompareSide"];
            player_b: components["schemas"]["CompareSide"];
            /**
             * Stat Rows
             * @default []
             */
            stat_rows: {
                [key: string]: unknown;
            }[];
            /**
             * Role Comparison
             * @default {}
             */
            role_comparison: {
                [key: string]: unknown;
            };
            /**
             * Why Higher
             * @default
             */
            why_higher: string;
            /**
             * Confidence Warnings
             * @default []
             */
            confidence_warnings: string[];
        };
        /** CompareSide */
        CompareSide: {
            identity: components["schemas"]["PlayerIdentity"];
            /**
             * Role Ratings
             * @default []
             */
            role_ratings: components["schemas"]["RoleRatingSummary"][];
            /**
             * Substats
             * @default []
             */
            substats: components["schemas"]["SubStat"][];
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleBadge"][];
            market?: components["schemas"]["MarketPanel"] | null;
            context?: components["schemas"]["ContextPanel"] | null;
            /**
             * Confidence
             * @default unknown
             */
            confidence: string;
        };
        /** ConcernMeta */
        ConcernMeta: {
            /** Key */
            key: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description?: string | null;
        };
        /** ContextDimMeta */
        ContextDimMeta: {
            /** Key */
            key: string;
            /** Explanation */
            explanation: string;
        };
        /** ContextPanel */
        ContextPanel: {
            /** League Strength */
            league_strength?: number | null;
            /** Team Strength */
            team_strength?: number | null;
            /** Opposition Quality */
            opposition_quality?: number | null;
            /** Competition Stakes */
            competition_stakes?: number | null;
            /** Role Usage */
            role_usage?: number | null;
            /** Sample Reliability */
            sample_reliability?: number | null;
            /** Translation Risk */
            translation_risk?: string | null;
            /** Sample Confidence */
            sample_confidence?: string | null;
            /** Minutes */
            minutes?: number | null;
            /**
             * Explanation
             * @default {}
             */
            explanation: {
                [key: string]: unknown;
            };
        };
        /** DataSource */
        DataSource: {
            /** Source Name */
            source_name: string;
            /** Source Player Id */
            source_player_id?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** DataSourceMeta */
        DataSourceMeta: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Url */
            url?: string | null;
            /** Note */
            note: string;
        };
        /** FaceStat */
        FaceStat: {
            /** Group Key */
            group_key: string;
            /** Group Label */
            group_label: string;
            /** Score */
            score?: number | null;
            /** Confidence */
            confidence: string;
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["SubStat"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestResult */
        IngestResult: {
            /** Run Id */
            run_id: number;
            /** Source */
            source: string;
            /** Players */
            players: number;
            /** Metrics */
            metrics: number;
            /** Quality Errors */
            quality_errors: number;
            /** Quality Warnings */
            quality_warnings: number;
        };
        /** MarketPanel */
        MarketPanel: {
            /** Public Value Eur */
            public_value_eur?: number | null;
            /** Model Value Low Eur */
            model_value_low_eur?: number | null;
            /** Model Value High Eur */
            model_value_high_eur?: number | null;
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
            /**
             * Confidence
             * @default unknown
             */
            confidence: string;
            /**
             * Label
             * @default unknown
             */
            label: string;
            /**
             * Manual Review Required
             * @default false
             */
            manual_review_required: boolean;
            /** Version */
            version?: string | null;
            /**
             * Explanation
             * @default {}
             */
            explanation: {
                [key: string]: unknown;
            };
        };
        /** MethodologyResponse */
        MethodologyResponse: {
            /** Scope */
            scope: string;
            /** Rating Version */
            rating_version: string;
            /** Playstyle Version */
            playstyle_version: string;
            /** Market Version */
            market_version: string;
            /** Formula */
            formula: string;
            /**
             * Roles
             * @default []
             */
            roles: components["schemas"]["RoleMeta"][];
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleMeta"][];
            /**
             * Concerns
             * @default []
             */
            concerns: components["schemas"]["ConcernMeta"][];
            /**
             * Context Dimensions
             * @default []
             */
            context_dimensions: components["schemas"]["ContextDimMeta"][];
            /**
             * Data Sources
             * @default []
             */
            data_sources: components["schemas"]["DataSourceMeta"][];
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /** Last Updated */
            last_updated?: string | null;
        };
        /** Paginated[PlayerSearchCard] */
        Paginated_PlayerSearchCard_: {
            /** Items */
            items: components["schemas"]["PlayerSearchCard"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PlayerCardResponse */
        PlayerCardResponse: {
            identity: components["schemas"]["PlayerIdentity"];
            /** Season */
            season: string;
            /** Confidence */
            confidence: string;
            /** Best Role */
            best_role?: string | null;
            /**
             * Face Stats
             * @default []
             */
            face_stats: components["schemas"]["FaceStat"][];
            /**
             * Substats
             * @default []
             */
            substats: components["schemas"]["SubStat"][];
            /**
             * Role Ratings
             * @default []
             */
            role_ratings: components["schemas"]["RoleRatingSummary"][];
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleBadge"][];
            /**
             * Concerns
             * @default []
             */
            concerns: components["schemas"]["PlaystyleBadge"][];
            market?: components["schemas"]["MarketPanel"] | null;
            /**
             * Strengths
             * @default []
             */
            strengths: components["schemas"]["StrengthConcern"][];
            /**
             * Concerns Text
             * @default []
             */
            concerns_text: components["schemas"]["StrengthConcern"][];
            context?: components["schemas"]["ContextPanel"] | null;
            /**
             * Data Sources
             * @default []
             */
            data_sources: components["schemas"]["DataSource"][];
            /** Last Updated */
            last_updated?: string | null;
            /** Rating Version */
            rating_version?: string | null;
        };
        /** PlayerIdentity */
        PlayerIdentity: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Age */
            age?: number | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Preferred Foot */
            preferred_foot?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Primary Position */
            primary_position?: string | null;
            /**
             * Secondary Positions
             * @default []
             */
            secondary_positions: string[];
            /** Position Group */
            position_group?: string | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
        };
        /** PlayerPlaystylesResponse */
        PlayerPlaystylesResponse: {
            /** Player Id */
            player_id: number;
            /** Season */
            season: string;
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleBadge"][];
            /**
             * Concerns
             * @default []
             */
            concerns: components["schemas"]["PlaystyleBadge"][];
        };
        /** PlayerSearchCard */
        PlayerSearchCard: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Age */
            age?: number | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Primary Position */
            primary_position?: string | null;
            /** Position Group */
            position_group?: string | null;
            /** Best Role */
            best_role?: string | null;
            /** Best Role Display */
            best_role_display?: string | null;
            /** Best Role Score */
            best_role_score?: number | null;
            /**
             * Confidence
             * @default unknown
             */
            confidence: string;
            /**
             * Top Playstyles
             * @default []
             */
            top_playstyles: string[];
            /** Minutes */
            minutes?: number | null;
            /** Market Label */
            market_label?: string | null;
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
        };
        /** PlaystyleBadge */
        PlaystyleBadge: {
            /** Playstyle Key */
            playstyle_key: string;
            /** Display Name */
            display_name: string;
            /** Category */
            category: string;
            /** Tier */
            tier?: string | null;
            /** Confidence */
            confidence: string;
            /**
             * Is Concern
             * @default false
             */
            is_concern: boolean;
            /**
             * Why Applied
             * @default {}
             */
            why_applied: {
                [key: string]: unknown;
            };
            /**
             * Supporting Metrics
             * @default []
             */
            supporting_metrics: {
                [key: string]: unknown;
            }[];
        };
        /** PlaystyleMeta */
        PlaystyleMeta: {
            /** Key */
            key: string;
            /** Display Name */
            display_name: string;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
        };
        /** RatingRunSummary */
        RatingRunSummary: {
            /** Id */
            id: number;
            /** Run Type */
            run_type: string;
            /** Version */
            version: string;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Affected Players Count */
            affected_players_count?: number | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Config Hashes
             * @default {}
             */
            config_hashes: {
                [key: string]: unknown;
            };
            /**
             * Source Snapshot Ids
             * @default []
             */
            source_snapshot_ids: string[];
        };
        /** RecomputeResult */
        RecomputeResult: {
            /** Run Id */
            run_id: number;
            /** Affected */
            affected: number;
            /** Seasons */
            seasons: number;
            /**
             * Outlier Check
             * @default {}
             */
            outlier_check: {
                [key: string]: unknown;
            };
        };
        /** RoleGroupMeta */
        RoleGroupMeta: {
            /** Key */
            key: string;
            /** Weight */
            weight: number;
        };
        /** RoleLeaderboard */
        RoleLeaderboard: {
            /** Role Key */
            role_key: string;
            /** Display Name */
            display_name: string;
            /** Position Group */
            position_group: string;
            /** Description */
            description?: string | null;
            /** Season */
            season: string;
            /** Rating Version */
            rating_version: string;
            /** Total */
            total: number;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["RoleRankingRow"][];
        };
        /** RoleMeta */
        RoleMeta: {
            /** Role Key */
            role_key: string;
            /** Display Name */
            display_name: string;
            /** Position Group */
            position_group: string;
            /** Description */
            description?: string | null;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["RoleGroupMeta"][];
        };
        /** RoleRankingRow */
        RoleRankingRow: {
            /** Rank */
            rank: number;
            /** Player Id */
            player_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Age */
            age?: number | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Final Score */
            final_score: number;
            /** Confidence */
            confidence: string;
            /**
             * Top Playstyles
             * @default []
             */
            top_playstyles: string[];
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
        };
        /** RoleRatingDetail */
        RoleRatingDetail: {
            /** Player Id */
            player_id: number;
            /** Season */
            season: string;
            /** Rating Version */
            rating_version: string;
            /**
             * Ratings
             * @default []
             */
            ratings: components["schemas"]["RoleRatingSummary"][];
            /**
             * Audits
             * @default []
             */
            audits: components["schemas"]["AuditBreakdown"][];
        };
        /** RoleRatingSummary */
        RoleRatingSummary: {
            /** Role Key */
            role_key: string;
            /** Display Name */
            display_name: string;
            /** Final Score */
            final_score: number;
            /** Raw Score */
            raw_score: number;
            /** Context Adjusted Score */
            context_adjusted_score: number;
            /** Confidence */
            confidence: string;
            /** Rank In Peer Group */
            rank_in_peer_group?: number | null;
            /**
             * Is Best
             * @default false
             */
            is_best: boolean;
        };
        /** SimilarGroup */
        SimilarGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Players
             * @default []
             */
            players: components["schemas"]["SimilarPlayer"][];
        };
        /** SimilarPlayer */
        SimilarPlayer: {
            /** Player Id */
            player_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Age */
            age?: number | null;
            /** Best Role */
            best_role?: string | null;
            /** Best Role Score */
            best_role_score?: number | null;
            /** Similarity */
            similarity: number;
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** SimilarResponse */
        SimilarResponse: {
            /** Player Id */
            player_id: number;
            /** Season */
            season: string;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["SimilarGroup"][];
        };
        /** StrengthConcern */
        StrengthConcern: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Score */
            score?: number | null;
        };
        /** SubStat */
        SubStat: {
            /** Name */
            name: string;
            /** Display */
            display: string;
            /** Unit */
            unit: string;
            /** Per90 Value */
            per90_value?: number | null;
            /** Percentile */
            percentile?: number | null;
            /** Score */
            score?: number | null;
            /**
             * Present
             * @default true
             */
            present: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_players_api_players_get: {
        parameters: {
            query?: {
                q?: string | null;
                age_min?: number | null;
                age_max?: number | null;
                position_group?: string | null;
                role?: string | null;
                league?: string | null;
                club?: string | null;
                nationality?: string | null;
                min_minutes?: number | null;
                rolefit_min?: number | null;
                rolefit_max?: number | null;
                playstyle?: string | null;
                value_min?: number | null;
                value_max?: number | null;
                sort?: string;
                /** @description 'mvp' (default) filters to the U23 EU att/mid universe; 'all' includes everyone */
                universe?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paginated_PlayerSearchCard_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_api_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_ratings_api_players__player_id__ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRatingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_playstyles_api_players__player_id__playstyles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPlaystylesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_market_api_players__player_id__market_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketPanel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_similar_players_api_players__player_id__similar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    role_rankings_api_roles__role_key__rankings_get: {
        parameters: {
            query?: {
                age_min?: number | null;
                age_max?: number | null;
                league?: string | null;
                min_minutes?: number | null;
                min_confidence?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                role_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleLeaderboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_compare_get: {
        parameters: {
            query: {
                player_a: number;
                player_b: number;
                role_key?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    methodology_api_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodologyResponse"];
                };
            };
        };
    };
    trigger_ingest_api_admin_ingest_post: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_recompute_api_admin_recompute_ratings_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rating_runs_api_admin_rating_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
