/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Players */
        get: operations["search_players_api_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_api_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Ratings */
        get: operations["get_player_ratings_api_players__player_id__ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/playstyles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Playstyles */
        get: operations["get_player_playstyles_api_players__player_id__playstyles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Market */
        get: operations["get_player_market_api_players__player_id__market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Similar Players */
        get: operations["get_similar_players_api_players__player_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{role_key}/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Role Rankings */
        get: operations["role_rankings_api_roles__role_key__rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Methodology */
        get: operations["methodology_api_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Ingest */
        post: operations["trigger_ingest_api_admin_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/recompute-ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Recompute */
        post: operations["trigger_recompute_api_admin_recompute_ratings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rating-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rating Runs */
        get: operations["rating_runs_api_admin_rating_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_admin_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ingestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingestion Runs */
        get: operations["ingestion_runs_api_admin_ingestion_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ingestion-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingestion Run */
        get: operations["ingestion_run_api_admin_ingestion_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quarantine */
        get: operations["quarantine_api_admin_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/snapshots/{snapshot_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Snapshot */
        get: operations["diff_snapshot_api_admin_snapshots__snapshot_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/freshness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Freshness */
        get: operations["source_freshness_api_admin_freshness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Coverage */
        get: operations["source_coverage_api_admin_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditBreakdown */
        AuditBreakdown: {
            /** Role Key */
            role_key: string;
            /**
             * Metric Breakdown
             * @default {}
             */
            metric_breakdown: {
                [key: string]: unknown;
            };
            /**
             * Context Breakdown
             * @default {}
             */
            context_breakdown: {
                [key: string]: unknown;
            };
            /**
             * Confidence Breakdown
             * @default {}
             */
            confidence_breakdown: {
                [key: string]: unknown;
            };
            /**
             * Penalties
             * @default {}
             */
            penalties: {
                [key: string]: unknown;
            };
            /** Explanation Text */
            explanation_text?: string | null;
        };
        /**
         * CalibrationMeta
         * @description Compact, evidence-honest calibration status for the Methodology surface.
         *
         *     When calibration cannot be evaluated in this environment, ``available`` is False and
         *     ``status`` is ``inconclusive`` — totals stay zero and ``config_hash`` is null rather than
         *     fabricating a successful result or hiding the section.
         */
        CalibrationMeta: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Suite Id */
            suite_id?: string | null;
            /** Suite Version */
            suite_version?: string | null;
            /** Calibration Version */
            calibration_version?: string | null;
            /** Rating Version */
            rating_version?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "warn" | "fail" | "inconclusive";
            /**
             * @default {
             *       "passed": 0,
             *       "warned": 0,
             *       "failed": 0,
             *       "inconclusive": 0,
             *       "total": 0
             *     }
             */
            benchmarks: components["schemas"]["CalibrationSummary"];
            /**
             * @default {
             *       "passed": 0,
             *       "warned": 0,
             *       "failed": 0,
             *       "inconclusive": 0,
             *       "total": 0
             *     }
             */
            scenarios: components["schemas"]["CalibrationSummary"];
            /** Methodology Note */
            methodology_note: string;
            /** Pilot Coverage Limitation */
            pilot_coverage_limitation: string;
            /** Config Hash */
            config_hash?: string | null;
        };
        /** CalibrationSummary */
        CalibrationSummary: {
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Warned
             * @default 0
             */
            warned: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Inconclusive
             * @default 0
             */
            inconclusive: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Season */
            season: string;
            /** Role Key */
            role_key?: string | null;
            /** Role Display */
            role_display?: string | null;
            player_a: components["schemas"]["CompareSide"];
            player_b: components["schemas"]["CompareSide"];
            /**
             * Stat Rows
             * @default []
             */
            stat_rows: {
                [key: string]: unknown;
            }[];
            /**
             * Role Comparison
             * @default {}
             */
            role_comparison: {
                [key: string]: unknown;
            };
            /**
             * Why Higher
             * @default
             */
            why_higher: string;
            /**
             * Confidence Warnings
             * @default []
             */
            confidence_warnings: string[];
        };
        /** CompareSide */
        CompareSide: {
            identity: components["schemas"]["PlayerIdentity"];
            /**
             * Role Ratings
             * @default []
             */
            role_ratings: components["schemas"]["RoleRatingSummary"][];
            /**
             * Substats
             * @default []
             */
            substats: components["schemas"]["SubStat"][];
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleBadge"][];
            market?: components["schemas"]["MarketPanel"] | null;
            context?: components["schemas"]["ContextPanel"] | null;
            /**
             * Confidence
             * @default unknown
             */
            confidence: string;
        };
        /** ConcernMeta */
        ConcernMeta: {
            /** Key */
            key: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description?: string | null;
        };
        /** ContextDimMeta */
        ContextDimMeta: {
            /** Key */
            key: string;
            /** Explanation */
            explanation: string;
        };
        /** ContextPanel */
        ContextPanel: {
            /** League Strength */
            league_strength?: number | null;
            /** Team Strength */
            team_strength?: number | null;
            /** Opposition Quality */
            opposition_quality?: number | null;
            /** Competition Stakes */
            competition_stakes?: number | null;
            /** Role Usage */
            role_usage?: number | null;
            /** Sample Reliability */
            sample_reliability?: number | null;
            /** Translation Risk */
            translation_risk?: string | null;
            /** Sample Confidence */
            sample_confidence?: string | null;
            /** Minutes */
            minutes?: number | null;
            /** Appearances */
            appearances?: number | null;
            /** Starts */
            starts?: number | null;
            /** Data Source */
            data_source?: string | null;
            /** Data Type */
            data_type?: string | null;
            /** Data Last Updated */
            data_last_updated?: string | null;
            /** Matches Covered */
            matches_covered?: number | null;
            /** Known Total Matches */
            known_total_matches?: number | null;
            /** Competition Coverage Pct */
            competition_coverage_pct?: number | null;
            /** Data Recency Days */
            data_recency_days?: number | null;
            /** Sample Size Confidence */
            sample_size_confidence?: string | null;
            /** Coverage Confidence */
            coverage_confidence?: string | null;
            /** League Adjustment Confidence */
            league_adjustment_confidence?: string | null;
            /** Role Similarity Confidence */
            role_similarity_confidence?: string | null;
            /** Overall Rating Confidence */
            overall_rating_confidence?: string | null;
            /**
             * Uses Event Data
             * @default false
             */
            uses_event_data: boolean;
            /**
             * Uses Basic Statistics
             * @default false
             */
            uses_basic_statistics: boolean;
            /**
             * Uses Modeled Values
             * @default false
             */
            uses_modeled_values: boolean;
            /**
             * Uses Demo Data
             * @default false
             */
            uses_demo_data: boolean;
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /** Attribution */
            attribution?: string | null;
            /**
             * Explanation
             * @default {}
             */
            explanation: {
                [key: string]: unknown;
            };
        };
        /** DataSource */
        DataSource: {
            /** Source Name */
            source_name: string;
            /** Source Player Id */
            source_player_id?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Provider Display Name */
            provider_display_name?: string | null;
            /** Data Type */
            data_type?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /** License Url */
            license_url?: string | null;
            /** Attribution */
            attribution?: string | null;
        };
        /** DataSourceMeta */
        DataSourceMeta: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Url */
            url?: string | null;
            /** Note */
            note: string;
        };
        /**
         * DiscoverySearchResponse
         * @description One page of Discovery results, plus which ordering produced them.
         *
         *     The five pagination fields are exactly the ones ``Paginated`` has always
         *     carried, in the same shape, so every existing client keeps working unchanged.
         *     ``ranking`` is additive.
         */
        DiscoverySearchResponse: {
            /** Items */
            items: components["schemas"]["PlayerSearchCard"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
            ranking: components["schemas"]["RankingExplanation"];
        };
        /** FaceStat */
        FaceStat: {
            /** Group Key */
            group_key: string;
            /** Group Label */
            group_label: string;
            /** Score */
            score?: number | null;
            /** Confidence */
            confidence: string;
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["SubStat"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestResult */
        IngestResult: {
            /** Run Id */
            run_id: number;
            /** Source */
            source: string;
            /** Players */
            players: number;
            /** Metrics */
            metrics: number;
            /** Quality Errors */
            quality_errors: number;
            /** Quality Warnings */
            quality_warnings: number;
        };
        /** MarketPanel */
        MarketPanel: {
            /** Public Value Eur */
            public_value_eur?: number | null;
            /** Model Value Low Eur */
            model_value_low_eur?: number | null;
            /** Model Value High Eur */
            model_value_high_eur?: number | null;
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
            /**
             * Confidence
             * @default unknown
             */
            confidence: string;
            /**
             * Label
             * @default unknown
             */
            label: string;
            /**
             * Manual Review Required
             * @default false
             */
            manual_review_required: boolean;
            /** Version */
            version?: string | null;
            /**
             * Explanation
             * @default {}
             */
            explanation: {
                [key: string]: unknown;
            };
        };
        /** MethodologyResponse */
        MethodologyResponse: {
            /** Scope */
            scope: string;
            /** Rating Version */
            rating_version: string;
            /** Playstyle Version */
            playstyle_version: string;
            /** Market Version */
            market_version: string;
            /** Formula */
            formula: string;
            /**
             * Roles
             * @default []
             */
            roles: components["schemas"]["RoleMeta"][];
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleMeta"][];
            /**
             * Concerns
             * @default []
             */
            concerns: components["schemas"]["ConcernMeta"][];
            /**
             * Context Dimensions
             * @default []
             */
            context_dimensions: components["schemas"]["ContextDimMeta"][];
            /**
             * Data Sources
             * @default []
             */
            data_sources: components["schemas"]["DataSourceMeta"][];
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            calibration?: components["schemas"]["CalibrationMeta"] | null;
            /** Last Updated */
            last_updated?: string | null;
        };
        /** PlayerCardResponse */
        PlayerCardResponse: {
            identity: components["schemas"]["PlayerIdentity"];
            /** Season */
            season: string;
            /** Confidence */
            confidence: string;
            /**
             * Analysis Status
             * @default profile_only
             */
            analysis_status: string;
            /**
             * Evidence Status
             * @default profile_only
             */
            evidence_status: string;
            /**
             * Has Rolefit Analysis
             * @default false
             */
            has_rolefit_analysis: boolean;
            /**
             * Is High Coverage
             * @default false
             */
            is_high_coverage: boolean;
            /** Best Role */
            best_role?: string | null;
            /**
             * Face Stats
             * @default []
             */
            face_stats: components["schemas"]["FaceStat"][];
            /**
             * Substats
             * @default []
             */
            substats: components["schemas"]["SubStat"][];
            /**
             * Role Ratings
             * @default []
             */
            role_ratings: components["schemas"]["RoleRatingSummary"][];
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleBadge"][];
            /**
             * Concerns
             * @default []
             */
            concerns: components["schemas"]["PlaystyleBadge"][];
            market?: components["schemas"]["MarketPanel"] | null;
            /**
             * Strengths
             * @default []
             */
            strengths: components["schemas"]["StrengthConcern"][];
            /**
             * Concerns Text
             * @default []
             */
            concerns_text: components["schemas"]["StrengthConcern"][];
            context?: components["schemas"]["ContextPanel"] | null;
            /**
             * Data Sources
             * @default []
             */
            data_sources: components["schemas"]["DataSource"][];
            /** Last Updated */
            last_updated?: string | null;
            /** Rating Version */
            rating_version?: string | null;
        };
        /** PlayerIdentity */
        PlayerIdentity: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Age */
            age?: number | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Preferred Foot */
            preferred_foot?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Primary Position */
            primary_position?: string | null;
            /**
             * Secondary Positions
             * @default []
             */
            secondary_positions: string[];
            /** Position Group */
            position_group?: string | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
        };
        /** PlayerPlaystylesResponse */
        PlayerPlaystylesResponse: {
            /** Player Id */
            player_id: number;
            /** Season */
            season: string;
            /**
             * Playstyles
             * @default []
             */
            playstyles: components["schemas"]["PlaystyleBadge"][];
            /**
             * Concerns
             * @default []
             */
            concerns: components["schemas"]["PlaystyleBadge"][];
        };
        /**
         * PlayerSearchCard
         * @description One Discovery result.
         *
         *     Two role contexts are reported side by side and never conflated:
         *
         *     * ``best_role*`` is the player's own highest stored role rating, independent of
         *       the query. It always describes the best role, whatever was filtered.
         *     * ``result_role*`` is the stored rating this result was actually filtered and
         *       ordered by, and is what a row displays. With no ``role`` filter it is the
         *       best-role rating; with ``role=<key>`` it is that role's stored rating.
         *
         *     ``result_role_source`` says which of the two the caller is looking at. Nothing
         *     here is recomputed: every score and confidence is the stored value.
         */
        PlayerSearchCard: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Season */
            season: string;
            /** Age */
            age?: number | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Primary Position */
            primary_position?: string | null;
            /** Position Group */
            position_group?: string | null;
            /** Best Role */
            best_role?: string | null;
            /** Best Role Display */
            best_role_display?: string | null;
            /** Best Role Score */
            best_role_score?: number | null;
            /**
             * Best Role Confidence
             * @default unknown
             */
            best_role_confidence: string;
            /** Result Role */
            result_role?: string | null;
            /** Result Role Display */
            result_role_display?: string | null;
            /** Result Role Score */
            result_role_score?: number | null;
            /**
             * Result Role Confidence
             * @default unknown
             */
            result_role_confidence: string;
            /**
             * Result Role Source
             * @default best_role
             */
            result_role_source: string;
            /**
             * Confidence
             * @default unknown
             */
            confidence: string;
            /**
             * Analysis Status
             * @default profile_only
             */
            analysis_status: string;
            /**
             * Evidence Status
             * @default profile_only
             */
            evidence_status: string;
            /**
             * Has Rolefit Analysis
             * @default false
             */
            has_rolefit_analysis: boolean;
            /**
             * Is High Coverage
             * @default false
             */
            is_high_coverage: boolean;
            /**
             * Top Playstyles
             * @default []
             */
            top_playstyles: string[];
            /** Minutes */
            minutes?: number | null;
            /** Represented Minutes */
            represented_minutes?: number | null;
            /** Market Label */
            market_label?: string | null;
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
        };
        /** PlaystyleBadge */
        PlaystyleBadge: {
            /** Playstyle Key */
            playstyle_key: string;
            /** Display Name */
            display_name: string;
            /** Category */
            category: string;
            /** Tier */
            tier?: string | null;
            /** Confidence */
            confidence: string;
            /**
             * Is Concern
             * @default false
             */
            is_concern: boolean;
            /**
             * Why Applied
             * @default {}
             */
            why_applied: {
                [key: string]: unknown;
            };
            /**
             * Supporting Metrics
             * @default []
             */
            supporting_metrics: {
                [key: string]: unknown;
            }[];
        };
        /** PlaystyleMeta */
        PlaystyleMeta: {
            /** Key */
            key: string;
            /** Display Name */
            display_name: string;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * RankingExplanation
         * @description Which ordering this page is in.
         *
         *     Ordering only. It does not describe recruitment quality, suitability or
         *     priority, and no filter appears here as a reason for rank: filters decide
         *     inclusion, and only the keys below decide order.
         */
        RankingExplanation: {
            /** Sort */
            sort: string;
            /** Sort Label */
            sort_label: string;
            /** Direction */
            direction: string;
            /** Direction Label */
            direction_label: string;
            /** Summary */
            summary: string;
            /**
             * Keys
             * @default []
             */
            keys: components["schemas"]["RankingKey"][];
            role_context: components["schemas"]["RankingRoleContext"];
            /** Missing Values */
            missing_values: string;
            /**
             * Tie Breakers
             * @default []
             */
            tie_breakers: components["schemas"]["RankingKey"][];
            /** Limitation */
            limitation: string;
        };
        /**
         * RankingKey
         * @description One ordering key, in the exact position the ``ORDER BY`` applies it.
         */
        RankingKey: {
            /** Position */
            position: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Direction */
            direction: string;
            /** Direction Label */
            direction_label: string;
            /** Role */
            role: string;
            /** Unit */
            unit: string;
            /** Rule */
            rule: string;
        };
        /**
         * RankingRoleContext
         * @description Which stored rating supplies the RoleFit shown on every result.
         *
         *     ``selected_role`` when the request carries ``role=<key>``: every result's
         *     ``result_role*`` group is that role. ``best_role`` otherwise: each player's own
         *     stored best role, which may differ from row to row.
         *
         *     Whether that rating also *ordered* the page depends on the active sort, and
         *     ``detail`` says which of the two it is. Under the RoleFit modes the applicable
         *     score and confidence are ordering keys; under Age, Expected Asking and Name they
         *     are displayed context and the named sort does the ordering.
         */
        RankingRoleContext: {
            /** Source */
            source: string;
            /** Role Key */
            role_key?: string | null;
            /** Role Display */
            role_display?: string | null;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
        };
        /** RatingRunSummary */
        RatingRunSummary: {
            /** Id */
            id: number;
            /** Run Type */
            run_type: string;
            /** Version */
            version: string;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Affected Players Count */
            affected_players_count?: number | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Config Hashes
             * @default {}
             */
            config_hashes: {
                [key: string]: unknown;
            };
            /**
             * Source Snapshot Ids
             * @default []
             */
            source_snapshot_ids: string[];
        };
        /** RecomputeResult */
        RecomputeResult: {
            /** Run Id */
            run_id: number;
            /** Affected */
            affected: number;
            /** Seasons */
            seasons: number;
            /**
             * Outlier Check
             * @default {}
             */
            outlier_check: {
                [key: string]: unknown;
            };
        };
        /** RoleGroupMeta */
        RoleGroupMeta: {
            /** Key */
            key: string;
            /** Weight */
            weight: number;
        };
        /** RoleLeaderboard */
        RoleLeaderboard: {
            /** Role Key */
            role_key: string;
            /** Display Name */
            display_name: string;
            /** Position Group */
            position_group: string;
            /** Description */
            description?: string | null;
            /** Season */
            season: string;
            /** Rating Version */
            rating_version: string;
            /** Total */
            total: number;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["RoleRankingRow"][];
        };
        /** RoleMeta */
        RoleMeta: {
            /** Role Key */
            role_key: string;
            /** Display Name */
            display_name: string;
            /** Position Group */
            position_group: string;
            /** Description */
            description?: string | null;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["RoleGroupMeta"][];
        };
        /** RoleRankingRow */
        RoleRankingRow: {
            /** Rank */
            rank: number;
            /** Player Id */
            player_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Age */
            age?: number | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Final Score */
            final_score: number;
            /** Confidence */
            confidence: string;
            /**
             * Top Playstyles
             * @default []
             */
            top_playstyles: string[];
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
        };
        /** RoleRatingDetail */
        RoleRatingDetail: {
            /** Player Id */
            player_id: number;
            /** Season */
            season: string;
            /** Rating Version */
            rating_version: string;
            /**
             * Ratings
             * @default []
             */
            ratings: components["schemas"]["RoleRatingSummary"][];
            /**
             * Audits
             * @default []
             */
            audits: components["schemas"]["AuditBreakdown"][];
        };
        /** RoleRatingSummary */
        RoleRatingSummary: {
            /** Role Key */
            role_key: string;
            /** Display Name */
            display_name: string;
            /** Final Score */
            final_score: number;
            /** Raw Score */
            raw_score: number;
            /** Context Adjusted Score */
            context_adjusted_score: number;
            /** Confidence */
            confidence: string;
            /** Rank In Peer Group */
            rank_in_peer_group?: number | null;
            /**
             * Is Best
             * @default false
             */
            is_best: boolean;
        };
        /** SimilarGroup */
        SimilarGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /**
             * Players
             * @default []
             */
            players: components["schemas"]["SimilarPlayer"][];
        };
        /** SimilarPlayer */
        SimilarPlayer: {
            /** Player Id */
            player_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Age */
            age?: number | null;
            /** Best Role */
            best_role?: string | null;
            /** Best Role Score */
            best_role_score?: number | null;
            /** Similarity */
            similarity: number;
            /** Expected Asking Low Eur */
            expected_asking_low_eur?: number | null;
            /** Expected Asking High Eur */
            expected_asking_high_eur?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** SimilarResponse */
        SimilarResponse: {
            /** Player Id */
            player_id: number;
            /** Season */
            season: string;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["SimilarGroup"][];
        };
        /** StrengthConcern */
        StrengthConcern: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Score */
            score?: number | null;
        };
        /** SubStat */
        SubStat: {
            /** Name */
            name: string;
            /** Display */
            display: string;
            /** Unit */
            unit: string;
            /** Per90 Value */
            per90_value?: number | null;
            /** Percentile */
            percentile?: number | null;
            /** Score */
            score?: number | null;
            /**
             * Present
             * @default true
             */
            present: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_players_api_players_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive literal substring across player name, club, league and primary position. When the WHOLE input is a configured club alias ('psg', 'spurs') the clubs it names are searched as well, so club abbreviations work here too. */
                q?: string | null;
                age_min?: number | null;
                age_max?: number | null;
                /** @description 'ATT', 'MID', 'DEF' or 'GK'. Validated against the domain's discoverable position groups; an unknown value is a 422. */
                position_group?: string | null;
                /** @description A configured role key. Only players with a STORED rating for it qualify, and the result's role context becomes that role: its stored score and confidence do the filtering, the ordering, the confidence tie-break and the display. An unknown role key is a 422. */
                role?: string | null;
                /** @description Case-insensitive literal substring over the competition's slug, name and country, so 'Premier League', 'eng' and 'England' all match. A small deterministic misspelling table is applied first (see configs/discovery/search_aliases_v1.yaml); there is no fuzzy matching. */
                league?: string | null;
                /** @description Case-insensitive literal substring over the team's slug and canonical name. A deterministic alias table resolves common abbreviations and nicknames first - 'psg', 'P.S.G.', 'spurs', 'thfc' - and an ambiguous abbreviation returns every club it defensibly names. Anything that is not a configured alias is searched as an ordinary substring; there is no fuzzy matching. */
                club?: string | null;
                /** @description Case-insensitive literal SUBSTRING of the stored nationality, so 'Eng' matches England. A player with no stored nationality fails an active predicate rather than matching. */
                nationality?: string | null;
                /** @description Whole season minutes, 0-10000 inclusive. Omit for no minutes threshold; 0 is a real accepted value, not 'unset'. Unrelated to the RoleFit scale. */
                min_minutes?: number | null;
                /** @description Applicable-role-context RoleFit floor on the authoritative 0-99 scale. */
                rolefit_min?: number | null;
                /** @description Applicable-role-context RoleFit ceiling on the authoritative 0-99 scale. */
                rolefit_max?: number | null;
                playstyle?: string | null;
                /** @description Absolute EUR. Requires a KNOWN expected-asking high endpoint, which must reach this floor; a player with unknown market information fails rather than being read as 0. */
                value_min?: number | null;
                /** @description Absolute EUR. Requires a KNOWN expected-asking low endpoint at or below this ceiling. Rejected when value_min exceeds value_max. */
                value_max?: number | null;
                /** @description One of: rolefit_desc, rolefit_asc, age_asc, age_desc, value_desc, value_asc, name_asc. Unknown values are a 422 rather than a silent fallback. RoleFit modes order by the applicable role context's stored score and break ties on its stored confidence; the asking-price modes order by expected_asking_low_eur with unknown lower bounds last in both directions. 'age_desc' is API-only: the Discovery Sort control does not offer it. */
                sort?: string;
                /** @description 'analyzed' (default), 'all_records', or 'high_coverage_u23'. Still a supported API capability; the Discovery UI no longer exposes a selector for it and always requests the default. */
                scope?: string | null;
                /** @description Legacy age filter: 'all' (default), 'u23', '24_26', '27_30', or '31_plus'. Superseded by the one-sided age_min / age_max bounds the Discovery age control writes; retained so existing callers keep working. */
                age_band?: string | null;
                /** @description Legacy alias: 'mvp' maps to high_coverage_u23; 'all' maps to all_records. Ignored when scope is supplied. */
                universe?: string | null;
                /** @description 1-based. A page past the end of a non-empty result set returns the last available page, and the response reports the page actually served. */
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_api_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerCardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_ratings_api_players__player_id__ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleRatingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_playstyles_api_players__player_id__playstyles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPlaystylesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_market_api_players__player_id__market_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketPanel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_similar_players_api_players__player_id__similar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    role_rankings_api_roles__role_key__rankings_get: {
        parameters: {
            query?: {
                age_min?: number | null;
                age_max?: number | null;
                league?: string | null;
                min_minutes?: number | null;
                min_confidence?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                role_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleLeaderboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_compare_get: {
        parameters: {
            query: {
                player_a: number;
                player_b: number;
                role_key?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    methodology_api_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodologyResponse"];
                };
            };
        };
    };
    trigger_ingest_api_admin_ingest_post: {
        parameters: {
            query?: {
                source?: string;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_recompute_api_admin_recompute_ratings_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rating_runs_api_admin_rating_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    providers_api_admin_providers_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingestion_runs_api_admin_ingestion_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingestion_run_api_admin_ingestion_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quarantine_api_admin_quarantine_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_snapshot_api_admin_snapshots__snapshot_id__diff_get: {
        parameters: {
            query: {
                other_snapshot_id: number;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_freshness_api_admin_freshness_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_coverage_api_admin_coverage_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
