"""initial schema

Creates every ScoutBoy table from the ORM metadata. Using create_all keeps this
baseline migration DB-agnostic (SQLite for local dev, Postgres via DATABASE_URL).
Later schema changes should be normal autogenerated Alembic revisions.

Revision ID: 0001_initial
Revises:
Create Date: 2024-01-15
"""

from __future__ import annotations

from alembic import op
from app.models.orm import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
